# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/si3gfried/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/si3gfried/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/si3gfried/Desktop/curse-tui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/si3gfried/Desktop/curse-tui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/si3gfried/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/si3gfried/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/si3gfried/Desktop/curse-tui/CMakeFiles /home/si3gfried/Desktop/curse-tui//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/si3gfried/Desktop/curse-tui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tui_test

# Build rule for target.
tui_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tui_test
.PHONY : tui_test

# fast build rule for target.
tui_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/build
.PHONY : tui_test/fast

TUI_test.o: TUI_test.cpp.o
.PHONY : TUI_test.o

# target to build an object file
TUI_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/TUI_test.cpp.o
.PHONY : TUI_test.cpp.o

TUI_test.i: TUI_test.cpp.i
.PHONY : TUI_test.i

# target to preprocess a source file
TUI_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/TUI_test.cpp.i
.PHONY : TUI_test.cpp.i

TUI_test.s: TUI_test.cpp.s
.PHONY : TUI_test.s

# target to generate assembly for a file
TUI_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/TUI_test.cpp.s
.PHONY : TUI_test.cpp.s

source/Animations.o: source/Animations.cpp.o
.PHONY : source/Animations.o

# target to build an object file
source/Animations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Animations.cpp.o
.PHONY : source/Animations.cpp.o

source/Animations.i: source/Animations.cpp.i
.PHONY : source/Animations.i

# target to preprocess a source file
source/Animations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Animations.cpp.i
.PHONY : source/Animations.cpp.i

source/Animations.s: source/Animations.cpp.s
.PHONY : source/Animations.s

# target to generate assembly for a file
source/Animations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Animations.cpp.s
.PHONY : source/Animations.cpp.s

source/Focus.o: source/Focus.cpp.o
.PHONY : source/Focus.o

# target to build an object file
source/Focus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Focus.cpp.o
.PHONY : source/Focus.cpp.o

source/Focus.i: source/Focus.cpp.i
.PHONY : source/Focus.i

# target to preprocess a source file
source/Focus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Focus.cpp.i
.PHONY : source/Focus.cpp.i

source/Focus.s: source/Focus.cpp.s
.PHONY : source/Focus.s

# target to generate assembly for a file
source/Focus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Focus.cpp.s
.PHONY : source/Focus.cpp.s

source/Misc_functions.o: source/Misc_functions.cpp.o
.PHONY : source/Misc_functions.o

# target to build an object file
source/Misc_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Misc_functions.cpp.o
.PHONY : source/Misc_functions.cpp.o

source/Misc_functions.i: source/Misc_functions.cpp.i
.PHONY : source/Misc_functions.i

# target to preprocess a source file
source/Misc_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Misc_functions.cpp.i
.PHONY : source/Misc_functions.cpp.i

source/Misc_functions.s: source/Misc_functions.cpp.s
.PHONY : source/Misc_functions.s

# target to generate assembly for a file
source/Misc_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Misc_functions.cpp.s
.PHONY : source/Misc_functions.cpp.s

source/TUI.o: source/TUI.cpp.o
.PHONY : source/TUI.o

# target to build an object file
source/TUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/TUI.cpp.o
.PHONY : source/TUI.cpp.o

source/TUI.i: source/TUI.cpp.i
.PHONY : source/TUI.i

# target to preprocess a source file
source/TUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/TUI.cpp.i
.PHONY : source/TUI.cpp.i

source/TUI.s: source/TUI.cpp.s
.PHONY : source/TUI.s

# target to generate assembly for a file
source/TUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/TUI.cpp.s
.PHONY : source/TUI.cpp.s

source/Timer.o: source/Timer.cpp.o
.PHONY : source/Timer.o

# target to build an object file
source/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Timer.cpp.o
.PHONY : source/Timer.cpp.o

source/Timer.i: source/Timer.cpp.i
.PHONY : source/Timer.i

# target to preprocess a source file
source/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Timer.cpp.i
.PHONY : source/Timer.cpp.i

source/Timer.s: source/Timer.cpp.s
.PHONY : source/Timer.s

# target to generate assembly for a file
source/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tui_test.dir/build.make CMakeFiles/tui_test.dir/source/Timer.cpp.s
.PHONY : source/Timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tui_test"
	@echo "... TUI_test.o"
	@echo "... TUI_test.i"
	@echo "... TUI_test.s"
	@echo "... source/Animations.o"
	@echo "... source/Animations.i"
	@echo "... source/Animations.s"
	@echo "... source/Focus.o"
	@echo "... source/Focus.i"
	@echo "... source/Focus.s"
	@echo "... source/Misc_functions.o"
	@echo "... source/Misc_functions.i"
	@echo "... source/Misc_functions.s"
	@echo "... source/TUI.o"
	@echo "... source/TUI.i"
	@echo "... source/TUI.s"
	@echo "... source/Timer.o"
	@echo "... source/Timer.i"
	@echo "... source/Timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

